import { mermaidLabel } from "./mermaid.js";

const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";

export interface Components {
  nodes: string[];
  edges: { from: string; to: string }[];
}

export function parseComponentsBlock(trf: string): Components | null {
  const m = /```easyprm:components\n([\s\S]*?)```/.exec(trf);
  if (!m) return null;
  const nodes = new Set<string>();
  const edges: { from: string; to: string }[] = [];
  for (const raw of m[1].split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const parts = line.split(/\s*->\s*/).map((p) => p.trim()).filter(Boolean);
    if (parts.length >= 2) {
      for (const p of parts) nodes.add(p);
      for (let i = 0; i < parts.length - 1; i++) {
        edges.push({ from: parts[i], to: parts[i + 1] });
      }
    } else if (parts.length === 1) {
      nodes.add(parts[0]);
    }
  }
  return { nodes: [...nodes], edges };
}

function sanitize(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, "_");
}

export function renderArchitecture(trf: string): string {
  const parsed = parseComponentsBlock(trf);
  if (!parsed) {
    return `${BANNER}

# Architecture

_No \`easyprm:components\` block found in docs/trf.md._ Add a fenced block like:

\`\`\`easyprm:components
api
db
api -> db
\`\`\`
`;
  }
  const lines = ["graph TD"];
  for (const n of parsed.nodes) lines.push(`  ${sanitize(n)}["${mermaidLabel(n)}"]`);
  for (const e of parsed.edges) lines.push(`  ${sanitize(e.from)} --> ${sanitize(e.to)}`);

  return `${BANNER}

# Architecture

\`\`\`mermaid
${lines.join("\n")}
\`\`\`
`;
}
