const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";

export interface Components {
  nodes: string[];
  edges: { from: string; to: string }[];
}

export function parseComponentsBlock(trf: string): Components | null {
  const m = /```easyprm:components\n([\s\S]*?)```/.exec(trf);
  if (!m) return null;
  const nodes = new Set<string>();
  const edges: { from: string; to: string }[] = [];
  for (const raw of m[1].split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const edge = /^(.+?)\s*->\s*(.+)$/.exec(line);
    if (edge) {
      const from = edge[1].trim();
      const to = edge[2].trim();
      nodes.add(from);
      nodes.add(to);
      edges.push({ from, to });
    } else {
      nodes.add(line);
    }
  }
  return { nodes: [...nodes], edges };
}

function sanitize(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, "_");
}

export function renderArchitecture(trf: string): string {
  const parsed = parseComponentsBlock(trf);
  if (!parsed) {
    return `${BANNER}

# Architecture

_No \`easyprm:components\` block found in docs/trf.md._ Add a fenced block like:

\`\`\`easyprm:components
api
db
api -> db
\`\`\`
`;
  }
  const lines = ["graph TD"];
  for (const n of parsed.nodes) lines.push(`  ${sanitize(n)}["${n}"]`);
  for (const e of parsed.edges) lines.push(`  ${sanitize(e.from)} --> ${sanitize(e.to)}`);

  return `${BANNER}

# Architecture

\`\`\`mermaid
${lines.join("\n")}
\`\`\`
`;
}
