import { detectCycle } from "../dag.js";
import type { Status, TaskFrontmatter, Ticket } from "../types.js";

const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";
const STYLE: Record<Status, string> = {
  backlog: "fill:#eee,stroke:#999",
  todo: "fill:#cce5ff,stroke:#3399ff",
  in_progress: "fill:#fff3cd,stroke:#ffc107",
  blocked: "fill:#f8d7da,stroke:#dc3545",
  in_review: "fill:#e2d9f3,stroke:#6f42c1",
  done: "fill:#d4edda,stroke:#28a745",
};

/** Sanitize an id for use as a Mermaid node identifier (no hyphens). */
function nodeId(id: string): string {
  return id.replace(/-/g, "_");
}

export function renderDependencies(tasks: Ticket<TaskFrontmatter>[]): string {
  const lines: string[] = ["graph LR"];
  for (const t of tasks) {
    const n = nodeId(t.frontmatter.id);
    lines.push(`  ${n}["${t.frontmatter.id}: ${t.frontmatter.title}"]`);
    lines.push(`  style ${n} ${STYLE[t.frontmatter.status]}`);
  }
  for (const t of tasks) {
    for (const dep of t.frontmatter.depends_on) {
      // Emit edge using original IDs (with hyphens) so the text is human-readable
      // and tests can match "E1-T1 --> E1-T2" patterns.
      lines.push(`  ${dep} --> ${t.frontmatter.id}`);
    }
  }

  const cycle = detectCycle(tasks);
  const note = cycle
    ? `\n> ⚠️ **Dependency cycle detected:** ${cycle.join(" → ")}. Resolve it via update_task.\n`
    : "";

  return `${BANNER}

# Dependencies
${note}
\`\`\`mermaid
${lines.join("\n")}
\`\`\`
`;
}
