import { detectCycle } from "../dag.js";
import type { Status, TaskFrontmatter, EpicFrontmatter, Ticket } from "../types.js";
import { mermaidLabel } from "./mermaid.js";

const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";
const STYLE: Record<Status, string> = {
  backlog: "fill:#eee,stroke:#999",
  todo: "fill:#cce5ff,stroke:#3399ff",
  in_progress: "fill:#fff3cd,stroke:#ffc107",
  blocked: "fill:#f8d7da,stroke:#dc3545",
  in_review: "fill:#e2d9f3,stroke:#6f42c1",
  done: "fill:#d4edda,stroke:#28a745",
};

/** Sanitize an id for use as a Mermaid node identifier (no hyphens). */
function nodeId(id: string): string {
  return id.replace(/-/g, "_");
}

export function renderDependencies(
  tasks: Ticket<TaskFrontmatter>[],
  epics: Ticket<EpicFrontmatter>[] = [],
): string {
  const epicById = new Map(epics.map((e) => [e.frontmatter.id, e]));

  // Compute effective phase for a task (epic wins)
  function effectivePhase(t: Ticket<TaskFrontmatter>): string | undefined {
    return epicById.get(t.frontmatter.epic)?.frontmatter.phase ?? t.frontmatter.phase;
  }

  // Check if any task has a phase — if none do, use v0.1 flat output
  const anyPhased = tasks.some((t) => {
    const eff = effectivePhase(t);
    return eff !== undefined && eff !== null && eff !== "";
  });

  const cycle = detectCycle(tasks);
  const note = cycle
    ? `\n> ⚠️ **Dependency cycle detected:** ${cycle.join(" → ")}. Resolve it via update_task.\n`
    : "";

  if (!anyPhased || epics.length === 0) {
    // v0.1 flat output — no subgraphs
    const lines: string[] = ["graph LR"];
    for (const t of tasks) {
      const n = nodeId(t.frontmatter.id);
      lines.push(`  ${n}["${mermaidLabel(`${t.frontmatter.id}: ${t.frontmatter.title}`)}"]`);
      lines.push(`  style ${n} ${STYLE[t.frontmatter.status]}`);
    }
    for (const t of tasks) {
      for (const dep of t.frontmatter.depends_on) {
        lines.push(`  ${nodeId(dep)} --> ${nodeId(t.frontmatter.id)}`);
      }
    }
    return `${BANNER}

# Dependencies
${note}
\`\`\`mermaid
${lines.join("\n")}
\`\`\`
`;
  }

  // Phase-grouped output with subgraphs
  // Group tasks by effective phase
  const phaseGroups = new Map<string, Ticket<TaskFrontmatter>[]>();
  const unscoped: Ticket<TaskFrontmatter>[] = [];
  for (const t of tasks) {
    const eff = effectivePhase(t);
    if (eff) {
      if (!phaseGroups.has(eff)) phaseGroups.set(eff, []);
      phaseGroups.get(eff)!.push(t);
    } else {
      unscoped.push(t);
    }
  }

  const lines: string[] = ["graph LR"];

  // Emit subgraph blocks per phase
  for (const [phaseId, phaseTasks] of phaseGroups) {
    lines.push(`  subgraph ${phaseId}`);
    for (const t of phaseTasks) {
      const n = nodeId(t.frontmatter.id);
      lines.push(`    ${n}["${mermaidLabel(`${t.frontmatter.id}: ${t.frontmatter.title}`)}"]`);
      lines.push(`    style ${n} ${STYLE[t.frontmatter.status]}`);
    }
    lines.push("  end");
  }

  // Emit unscoped tasks (no subgraph)
  for (const t of unscoped) {
    const n = nodeId(t.frontmatter.id);
    lines.push(`  ${n}["${mermaidLabel(`${t.frontmatter.id}: ${t.frontmatter.title}`)}"]`);
    lines.push(`  style ${n} ${STYLE[t.frontmatter.status]}`);
  }

  // Emit all edges outside subgraphs
  for (const t of tasks) {
    for (const dep of t.frontmatter.depends_on) {
      lines.push(`  ${nodeId(dep)} --> ${nodeId(t.frontmatter.id)}`);
    }
  }

  return `${BANNER}

# Dependencies
${note}
\`\`\`mermaid
${lines.join("\n")}
\`\`\`
`;
}
