import { STATUSES } from "../types.js";
import type { Status, TaskFrontmatter, EpicFrontmatter, Ticket } from "../types.js";

const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";
const LABELS: Record<Status, string> = {
  backlog: "Backlog",
  todo: "Todo",
  in_progress: "In Progress",
  blocked: "Blocked",
  in_review: "In Review",
  done: "Done",
};

export function renderKanban(
  epics: Ticket<EpicFrontmatter>[],
  tasks: Ticket<TaskFrontmatter>[],
): string {
  const byStatus = (s: Status) => tasks.filter((t) => t.frontmatter.status === s);

  const board = STATUSES.map((s) => {
    const items = byStatus(s)
      .map((t) => `- ${t.frontmatter.id} ${t.frontmatter.title}`)
      .join("\n");
    return `### ${LABELS[s]} (${byStatus(s).length})\n\n${items || "_none_"}`;
  }).join("\n\n");

  const summary = epics
    .map((e) => {
      const et = tasks.filter((t) => t.frontmatter.epic === e.frontmatter.id);
      const done = et.filter((t) => t.frontmatter.status === "done").length;
      const pct = et.length ? Math.round((done / et.length) * 100) : 0;
      return `- **Epic ${e.frontmatter.id}** ${e.frontmatter.title}: ${done}/${et.length} done (${pct}%)`;
    })
    .join("\n");

  return `${BANNER}

# Kanban

## Progress by Epic

${summary || "_no epics yet_"}

## Board

${board}
`;
}
