import { STATUSES } from "../types.js";
import type { Status, TaskFrontmatter, EpicFrontmatter, Ticket } from "../types.js";
import { effectivePhaseOf } from "./utils.js";

const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";
const LABELS: Record<Status, string> = {
  backlog: "Backlog",
  todo: "Todo",
  in_progress: "In Progress",
  blocked: "Blocked",
  in_review: "In Review",
  done: "Done",
};

export function renderKanban(
  epics: Ticket<EpicFrontmatter>[],
  tasks: Ticket<TaskFrontmatter>[],
  activePhase: string | null = null,
  allPhases: { id: string; title: string }[] = [],
): string {
  const epicById = new Map(epics.map((e) => [e.frontmatter.id, e]));

  // Determine the set of tasks to show on the primary board
  const primaryTasks = activePhase
    ? tasks.filter((t) => effectivePhaseOf(t, epicById) === activePhase)
    : tasks;

  const byStatus = (s: Status, taskSet: Ticket<TaskFrontmatter>[]) =>
    taskSet.filter((t) => t.frontmatter.status === s);

  const board = STATUSES.map((s) => {
    const tasksForStatus = byStatus(s, primaryTasks);
    const items = tasksForStatus.map((t) => `- ${t.frontmatter.id} ${t.frontmatter.title}`).join("\n");
    return `### ${LABELS[s]} (${tasksForStatus.length})\n\n${items || "_none_"}`;
  }).join("\n\n");

  const summary = epics
    .map((e) => {
      const et = tasks.filter((t) => t.frontmatter.epic === e.frontmatter.id);
      const done = et.filter((t) => t.frontmatter.status === "done").length;
      const pct = et.length ? Math.round((done / et.length) * 100) : 0;
      return `- **Epic ${e.frontmatter.id}** ${e.frontmatter.title}: ${done}/${et.length} done (${pct}%)`;
    })
    .join("\n");

  let extras = "";

  if (activePhase) {
    // Other phases section
    const otherPhases = allPhases.filter((ph) => ph.id !== activePhase);
    if (otherPhases.length) {
      const otherLines = otherPhases.map((ph) => {
        const count = tasks.filter((t) => effectivePhaseOf(t, epicById) === ph.id).length;
        return `- **${ph.id} ${ph.title}:** ${count} task(s)`;
      }).join("\n");
      extras += `\n## Other phases\n\n${otherLines}\n`;
    }

    // Unscoped section (tasks with no effective phase)
    const unscopedTasks = tasks.filter((t) => {
      const eff = effectivePhaseOf(t, epicById);
      return eff === undefined || eff === null || eff === "";
    });
    if (unscopedTasks.length) {
      const unscopedBoard = STATUSES.map((s) => {
        const tasksForStatus = byStatus(s, unscopedTasks);
        if (!tasksForStatus.length) return null;
        const items = tasksForStatus.map((t) => `- ${t.frontmatter.id} ${t.frontmatter.title}`).join("\n");
        return `### ${LABELS[s]} (${tasksForStatus.length})\n\n${items}`;
      }).filter(Boolean).join("\n\n");
      extras += `\n## Unscoped\n\n${unscopedBoard}\n`;
    }
  }

  return `${BANNER}

# Kanban

## Progress by Epic

${summary || "_no epics yet_"}

## Board

${board}${extras}`;
}
