import type { Phase } from "../store/phases.js";
import type { TaskFrontmatter, EpicFrontmatter, Ticket } from "../types.js";

const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";

/** Pure renderer for phases.md. */
export function renderPhases(
  phases: Phase[],
  epics: Ticket<EpicFrontmatter>[],
  tasks: Ticket<TaskFrontmatter>[],
): string {
  if (!phases.length) {
    return `${BANNER}\n\n# Phases\n\n_No phases yet. Call create_phase to organize epics by release._\n`;
  }
  const epicById = new Map(epics.map((e) => [e.frontmatter.id, e]));
  const lines = phases.map((p) => {
    const phaseTasks = tasks.filter((t) => {
      const eff = epicById.get(t.frontmatter.epic)?.frontmatter.phase ?? t.frontmatter.phase;
      return eff === p.frontmatter.id;
    });
    const done = phaseTasks.filter((t) => t.frontmatter.status === "done").length;
    const total = phaseTasks.length;
    const pct = total ? Math.round((done / total) * 100) : 0;
    return `- **${p.frontmatter.id} ${p.frontmatter.title}** (${p.frontmatter.status}) — ${done}/${total} tasks (${pct}%) — ${p.frontmatter.goal}`;
  }).join("\n");
  return `${BANNER}\n\n# Phases\n\n${lines}\n`;
}
