import { getNextTask } from "../dag.js";
import type { TaskFrontmatter, EpicFrontmatter, Ticket } from "../types.js";
import type { Decision } from "../store/decisions.js";

const BANNER = "<!-- AUTO-GENERATED by easyprm — do not edit -->";

export function renderStatus(
  epics: Ticket<EpicFrontmatter>[],
  tasks: Ticket<TaskFrontmatter>[],
  decisions: Decision[] = [],
): string {
  const activeEpic = epics.find((e) => e.frontmatter.status === "in_progress");
  const inProgress = tasks.filter((t) => t.frontmatter.status === "in_progress");
  const blocked = tasks.filter((t) => t.frontmatter.status === "blocked");
  const next = getNextTask(tasks);

  const fmt = (t: Ticket<TaskFrontmatter>) => `${t.frontmatter.id} — ${t.frontmatter.title}`;
  const fmtEpic = (e: Ticket<EpicFrontmatter>) => `${e.frontmatter.id} ${e.frontmatter.title} (${e.frontmatter.status})`;

  const latestDecisions = [...decisions]
    .sort((a, b) => b.frontmatter.id.localeCompare(a.frontmatter.id))
    .slice(0, 3);
  const dBlock = latestDecisions.length
    ? `\n**Recent decisions:**\n${latestDecisions.map((d) => `- ${d.frontmatter.id} ${d.frontmatter.title} (${d.frontmatter.status})`).join("\n")}\n`
    : "";

  return `${BANNER}

# Status — Where Was I

**Active epic:** ${activeEpic ? `${activeEpic.frontmatter.id} ${activeEpic.frontmatter.title}` : "_none in progress_"}

**All epics:**
${epics.length ? epics.map((e) => `- ${fmtEpic(e)}`).join("\n") : "_no epics yet_"}

**In progress:**
${inProgress.length ? inProgress.map((t) => `- ${fmt(t)}`).join("\n") : "_nothing in progress_"}

**Blocked:**
${blocked.length ? blocked.map((t) => `- ${fmt(t)}`).join("\n") : "_none_"}

**Recommended next:** ${next.task ? fmt(next.task) : "—"}
${next.reason}${dBlock}`;
}
